services:
  db:
    image: postgres:16-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: ecommerce_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://ecommerce:ecommerce@db:5432/ecommerce
      JWT_SECRET: cambia-esto-por-un-secreto-largo-y-aleatorio
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata:
